### ISSUE TITLE
🐞 Vite compiler doesn't extract valid classes, even ones rightfully tagged as potential 

### ISSUE THREAD

**Issue by AristideBH** [master-co/css#109]
### What happened?

Upon server start, with debug activated, a lot of the classes I'm using are tagged as potential, but then not considered valid nor included in `master.css`.
As you can see in the log, even basic and valid classes like `w:100%`, `t:center`, `f:12` etc aren't applied. 
This goes on for every pages or components, the resulting mater.css only have 15 compiled classes.

Then, when I save a page (or component) in VSCode,  while the server is running, the HMR updates the page, 
and there, the styles are taken into account (without further debug infos)

Regarding MasterCssVitePlugin ,I get find the previously existing option to select here the outputed master.css should go, and it's now outputted inside my `node_modules/.vite` folder, while using pnpm.

Its also seems that the latest beta 95 dosn't include the types definitions for the compiler.

### Version

v2.0.0 beta 95 w/ Sveltekit 1.0.1

### Relevant log output

```shell
✓ import master.css.js configuration
15:26:29 [extract] 1 potential src/app.html
15:26:29 [extract] contents
15:26:29 [compile] 1 valid in 0.49ms (1 rules)
15:26:29 [compile] contents
15:26:29 [extract] 23 potential src/routes/+page.svelte
15:26:29 [extract] onMount(() grid-row:1/2 flex flex:col gabX:full w:100% aspect:16/9 obj:cover gabX:col bg:var(--code-background-color) p:20 sticky top:0 z:10 {p:1.5em;flex-basis:full;fg:white;text-decoration:none}>a t:center ai:center jc:center f:12 flex:row fg:white text-decoration:none:hover bg:var(--primary)
15:26:29 [compile] 4 valid in 9.03ms (5 rules)
15:26:29 [compile] contents flex flex:col sticky flex:row
...
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by 1aron** [comment]
In version `>=2.0.0-beta.86`, we use virtual module tech to import in-memory CSS files.

`vite.config.js`
```js
import { sveltekit } from '@sveltejs/kit/vite'
import { MasterCSSVitePlugin } from '@master/css.vite'

/** @type {import('vite').UserConfig} */
const config = {
    plugins: [
        sveltekit(),
        MasterCSSVitePlugin()
    ]
}

export default config
```
Import the virtual CSS module into `src/routes/+layout.svelte`:
```html
<script>
    import Header from "./Header.svelte";
    import "./styles.css";
    import "master.css";
</script>
```

Therefore, you won't get any visual output and you need to delete the previous `master.css` static file.

**Comment by 1aron** [comment]
@AristideBH At present, it is very likely that the `onMount(()` in the context crashed because of parsing the wrong class! We are working on this issue.

**Comment by AristideBH** [comment]
> Therefore, you won't get any visual output and you need to delete the previous `master.css` static file.

Thanks for the quick answer concerning the import and a possible solution.
I would test right away the import but as such little classes are being compiled, I can' really see the differnces !
Looking forward to test a possible work around ;)

Thanks Aron !

**Comment by AristideBH** [comment]
In addition, here's a link to the `src/routes/+page.svelte` 
https://github.com/AristideBH/noise-fr/blob/master/src/routes/%2Bpage.svelte

> @AristideBH At present, it is very likely that the `onMount(()` in the context crashed because of parsing the wrong class! We are working on this issue.

I just tested removing the `onMount import` and the actual call to it, but I don't have many more classes tagged as valid : 
```
...
16:33:09 [extract] 22 potential src/routes/+page.svelte
16:33:09 [extract] grid-row:1/2 flex flex:col gabX:full w:100% aspect:16/9 obj:cover gabX:col bg:var(--code-background-color) p:20 sticky top:0 z:10 {p:1.5em;flex-basis:full;fg:white;text-decoration:none}>a t:center ai:center jc:center f:12 flex:row fg:white text-decoration:none:hover bg:var(--primary)
16:33:09 [compile] 4 valid in 9.64ms (5 rules)
...
```

**Comment by 1aron** [comment]
> > Therefore, you won't get any visual output and you need to delete the previous `master.css` static file.
> 
> Thanks for the quick answer concerning the import and a possible solution. I would test right away the import but as such little classes are being compiled, I can' really see the differnces ! Looking forward to test a possible work around ;)
> 
> Thanks Aron !

Recently we will improve the output of the log, and we are also considering outputting a beautified CSS file somewhere asynchronously or through a Chrome Extension.

**Comment by 1aron** [comment]
> In addition, here's a link to the `src/routes/+page.svelte` https://github.com/AristideBH/noise-fr/blob/master/src/routes/%2Bpage.svelte
> 
> > @AristideBH At present, it is very likely that the `onMount(()` in the context crashed because of parsing the wrong class! We are working on this issue.
> 
> I just tested removing the `onMount import` and the actual call to it, but I don't have many more classes tagged as valid :
> 
> ```
> ...
> 16:33:09 [extract] 22 potential src/routes/+page.svelte
> 16:33:09 [extract] grid-row:1/2 flex flex:col gabX:full w:100% aspect:16/9 obj:cover gabX:col bg:var(--code-background-color) p:20 sticky top:0 z:10 {p:1.5em;flex-basis:full;fg:white;text-decoration:none}>a t:center ai:center jc:center f:12 flex:row fg:white text-decoration:none:hover bg:var(--primary)
> 16:33:09 [compile] 4 valid in 9.64ms (5 rules)
> ...
> ```

Understood, thanks for the full bug report, this is a big issue so we'll fix it by tomorrow!

**Comment by 1aron** [comment]
🎉 The issue has been fixed in [v2.0.0-beta.96](https://github.com/master-co/css/releases/tag/v2.0.0-beta.96)

**Comment by AristideBH** [comment]
Hey Aron, thanks for the quick fix
However, I just tried with the 96 beta (cleared my `node_modules` folder), but the results are the same as before .

See the debug output below for `src/routes/+page.svelte` :
```shell
14:30:32 [extract] 22 potential ..src/routes/+page.svelte..
14:30:32 [extract] grid-row:1/2,flex,flex:col,gabX:full,w:100%,aspect:16/9,obj:cover,gabX:col,bg:var(--code-background-color),p:20,sticky,top:0,z:10,t:center,ai:center,jc:center,f:12,flex:row,{p:1.5em;flex-basis:full;fg:white;text-decoration:none}>a,fg:white,text-decoration:none:hover,bg:var(--primary)
14:30:32 [compile] +4+ valid ..in.. 4.34ms ..(5.. ..rules)..
14:30:32 [compile] contents,flex,flex:col,sticky,flex:row
```

Right before this update I was able to see a `master.css` file created inside `node_module/.vite` folder, 
but after purging my node_modules and updating dependencies, this file is not created anymore : 
is it the expected behaviour for the " import in-memory CSS files" ?


Edit: typos

**Comment by 1aron** [comment]
> Hey Aron, thanks for the quick fix However, I just tried with the 96 beta (cleared my `node_modules` folder), but the results are the same as before .
> 
> See the debug output below for `src/routes/+page.svelte` :
> 
> ```
> 14:30:32 [extract] 22 potential ..src/routes/+page.svelte..
> 14:30:32 [extract] grid-row:1/2,flex,flex:col,gabX:full,w:100%,aspect:16/9,obj:cover,gabX:col,bg:var(--code-background-color),p:20,sticky,top:0,z:10,t:center,ai:center,jc:center,f:12,flex:row,{p:1.5em;flex-basis:full;fg:white;text-decoration:none}>a,fg:white,text-decoration:none:hover,bg:var(--primary)
> 14:30:32 [compile] +4+ valid ..in.. 4.34ms ..(5.. ..rules)..
> 14:30:32 [compile] contents,flex,flex:col,sticky,flex:row
> ```
> 
> Right before this update I was able to see a `master.css` file created inside `node_module/.vite` folder, but after purging my node_modules and updating dependencies, this file is not created anymore : is it the expected behaviour for the " import in-memory CSS files" ?
> 
> Edit: typos

@AristideBH Your test case passes, let's see if there are other exceptions causing the problem. The log output will look a bit confusing at the moment, please bear with me for another day.

That's right, it's in memory now.

**Comment by AristideBH** [comment]
@1aron Yeah, I've noticed the debug log was changing a bit ;)
No problem, I'll kindly wait the needed time,
Do not hesitate if any infos is needed ! (my test repo is still open and public)

**Comment by 1aron** [comment]
@AristideBH I found the problem. To remove this line: https://github.com/AristideBH/noise-fr/blob/master/master.css.js#L130 Arrays are now overwritten rather than extended.

**Comment by AristideBH** [comment]
Yeah ! Awesome !  Just tested and it's working as intented !
I feel dumb as I don't remember from where I copied this starter file...

Thanks a lot Aron <3
