### ISSUE TITLE
✨ [v2] default for predefined variables

### ISSUE THREAD

**Issue by oskar-gmerek** [master-co/css#110]
### Description

Currently we can predefine custom variables like that:

```
themes: {
 light: {
  colors: {
   primary: {
    10: colors.green['10'],
    50: colors.green['50'],
    90: colors.green['90']
   },
  },
 },
},
```

And then use them like:
`<div class="bg:primary-50">Test</div>`

But this will not work:
`<div class="bg:primary">Test</div>`

Idea here is to use key `default` to create a shortcut, for ex:

```
themes: {
 light: {
  colors: {
   primary: {
    default: colors.green['30']
    10: colors.green['10'],
    50: colors.green['50'],
    90: colors.green['90']
   },
  },
 },
},
```

Then this should be possible to use it like this:
`<div class="bg:primary">Test</div>`

**Comment by 1aron** [comment]
> ### Description
> Currently we can predefine custom variables like that:
> 
> ```
> themes: {
>  light: {
>   colors: {
>    primary: {
>     10: colors.green['10'],
>     50: colors.green['50'],
>     90: colors.green['90']
>    },
>   },
>  },
> },
> ```
> 
> And then use them like: `<div class="bg:primary-50">Test</div>`
> 
> But this will not work: `<div class="bg:primary">Test</div>`
> 
> Idea here is to use key `default` to create a shortcut, for ex:
> 
> ```
> themes: {
>  light: {
>   colors: {
>    primary: {
>     default: colors.green['30']
>     10: colors.green['10'],
>     50: colors.green['50'],
>     90: colors.green['90']
>    },
>   },
>  },
> },
> ```
> 
> Then this should be possible to use it like this: `<div class="bg:primary">Test</div>`

This feature is already available and will be included in the beta documentation.

```ts
colors: {
    primary: {
        '': 'green-30',
        10: 'green-10'
    }
}
```
