### ISSUE TITLE
✨ Style elements highlight for language service

### ISSUE THREAD

**Issue by itsezc** [master-co/css#113]
### Description

Currently there is no syntax highlighting integrated for Master style elements:

![image](https://user-images.githubusercontent.com/33750251/209453040-17f540f2-ff08-40e7-be9d-5f977864f6e7.png)

It would be nice to have a first class support out of the box for the style elements, including post composition API changes i.e. covering conditional class declarations too as it enhances the DX while using Master.

The auto hinting also does not work for `style-element`

**Comment by 0Miles** [comment]
🎉 The feature has been added in v2.1.23
