### ISSUE TITLE
✨ Add `defaultTheme` property to config

### ISSUE THREAD

**Issue by itsezc** [master-co/css#115]
### Description

Currently in Master v2 its possible to define themes; however, it's not possible to set the default theme, adding a property `defaults` and a child `theme` allowing for the default theme to be provided would be useful.

Example implementation in config:
```ts
// master.css.js
export default {
   defaults: {
	theme: 'screen'
   },
   themes: {
	xr: {},
	screen: {},
   },
}
```

This syntax could later extend to `scheme` and other properties.

**Comment by 1aron** [comment]
Use instead https://beta.css.master.co/docs/theme-service
