### ISSUE TITLE
📄 SvelteKit in frameworks

### ISSUE THREAD

**Issue by itsezc** [master-co/css#117]
### What is the improvement or update you wish to see?

Add documentation for SvelteKit 1.0 on the Master Docs. Sveltekit has grown in popularity and it would be nice to have official docs from Master.

**Comment by 1aron** [comment]
https://github.com/master-co/css/tree/beta/examples/svelte will be included in the upcoming 2.0 beta docs.

**Comment by 1aron** [comment]
https://beta.css.master.co/docs/guides/svelte/ahead-of-time
