### ISSUE TITLE
📄 Vite in build tools

### ISSUE THREAD

**Issue by itsezc** [master-co/css#118]
### What is the improvement or update you wish to see?

Add documentation for Vite on the Master Docs, currently this is missing and already released, so documenting this would be great for people unfamilar.

**Comment by 1aron** [comment]
https://github.com/master-co/css/tree/beta/examples/vite will be included in the upcoming 2.0 beta docs.

**Comment by Andres6936** [comment]
@1aron I think there is something wrong with the documentation, because when I follow the steps and run npm run dev I get the following error: 

```shellsession
> dev 
> vite


✗ Cannot find master.css.{ts,js,mjs,cjs} config
```

**Comment by 1aron** [comment]
> @1aron I think there is something wrong with the documentation, because when I follow the steps and run npm run dev I get the following error:
> 
> ```
> > dev 
> > vite
> 
> 
> ✗ Cannot find master.css.{ts,js,mjs,cjs} config
> ```

This is a bad terminal output, which has been improved in recent releases #163.

**Comment by 1aron** [comment]
https://beta.css.master.co/docs/guides/vite
