### ISSUE TITLE
✨ [beta] Playground with the latest beta release

### ISSUE THREAD

**Issue by oskar-gmerek** [master-co/css#121]
### Description

I think this may be easy to get. If I'm wrong then ignore it, please.

I found out that if something doesn't go as expected, it's hard to find what actually affects the error.

It would be useful to have an environment where you can easily copy-paste. Like the current playground for v1. This could result in more specific information in the issue ticket, plus it would give us the ability to quickly visualize the problem. And of course with the hope to get a v2 release quicker 🤪

**Comment by 1aron** [comment]
Agreed, we'll release beta.css.master.co as soon as possible in mid or end of January.

**Comment by 1aron** [comment]
It's available now at [sandbox.master.co](https://sandbox.master.co/).
