### ISSUE TITLE
🐞 Color previews aren't rendered correctly

### ISSUE THREAD

**Issue by 1aron** [master-co/css#125]
### What happened?

- The color token isn't previewed
- The HEX color isn't previewed

<img width="856" alt="Screenshot 2023-01-04 at 3 05 11 PM" src="https://user-images.githubusercontent.com/33840671/210501777-3a1c55db-7a7e-4591-b62a-fceed97adb0e.png">

The corresponding core API:

- `css.colorThemesMap`

### Version

v2.1.17

**Comment by 0Miles** [comment]
🎉 The bug has been fixed in v2.1.23
