### ISSUE TITLE
🐞 Nested `classes` configuration was not highlighted correctly

### ISSUE THREAD

**Issue by 1aron** [master-co/css#126]
### What happened?

<img width="867" alt="Screenshot 2023-01-04 at 3 11 16 PM" src="https://user-images.githubusercontent.com/33840671/210502597-5ddef703-dcae-453b-806d-0bd9a51a1b9a.png">

### Version

v2.1.17

**Comment by 0Miles** [comment]
🎉 The bug has been fixed in v2.1.20
