### ISSUE TITLE
✨ Auto-completion of color-related configuration

### ISSUE THREAD

**Issue by 1aron** [master-co/css#127]
### Description

- `config.themes.*.colors`
- `config.colors`

<img width="830" alt="Screenshot 2023-01-04 at 3 16 59 PM" src="https://user-images.githubusercontent.com/33840671/210503166-4235f7bf-d1f3-4cd8-bbe3-d6059b7d544c.png">

**Comment by 0Miles** [comment]
🎉 The feature has been added in v2.1.23
