### ISSUE TITLE
✨ Autocompletion for values, semantics, breakpoints, selectors, mediaQueries

### ISSUE THREAD

**Issue by 1aron** [master-co/css#129]
### Description

```js
{
    values: {
        Width: {
            '2x': '2rem',
            '3x': '3rem',
        },
        sm: '0.5rem'
    },
    semantics: {
        show: 'display:block',
        'hide-text': 'font-size:0px'
    },
    breakpoints: {
        tablet: 768,
        laptop: 1024,
        desktop: 1280,
    },
    selectors: {
        '>custom': '>div>:first+button'
    },
    mediaQueries: {
        watch: '(max-device-width:42mm) and (min-device-width:38mm)'
    },
}
```

**Comment by 1aron** [comment]
@0Miles You should make code-completion refer https://github.com/microsoft/vscode-css-languageservice/blob/main/src/data/webCustomData.ts

Same as #95 

<img width="728" alt="Screenshot 2023-01-10 at 4 54 31 PM" src="https://user-images.githubusercontent.com/33840671/211505615-d80e3848-9e58-432d-89b8-467edfb15d4b.png">

**Comment by 0Miles** [comment]
🎉 The feature has been added in v2.1.23
