### ISSUE TITLE
✨ VSCode: add setting for master.css.* file location

### ISSUE THREAD

**Issue by tve** [master-co/css#134]
### Description

The VSCode extension expects to find the master.css.* config file at the top of the workspace but that's not necessarily where it is located. In my project, the top of the repo has other stuff and the browser app that uses Master.CSS is further down the tree. If I put a master.css.ts symlink at the top level the extension works, but that's not exactly a clean solution. Please add a setting to provide a path or alternatively search up through the directory structure from the current file being edited to find the "closest" master.css.* config file.

**Comment by 0Miles** [comment]
🎉 The feature has been added in v2.1.23

Added config: `masterCSS.configFileLocation`
You can use a relative path to set the directory where `master.css.ts` is located
