### ISSUE TITLE
🐞 `vw` `vh` `min-vw` `min-vh` `max-vw` `max-vh` aren't highlighted

### ISSUE THREAD

**Issue by 1aron** [master-co/css#141]
### What happened?

<img width="797" alt="Screenshot 2023-01-13 at 2 58 36 AM" src="https://user-images.githubusercontent.com/33840671/212157514-c2f5bced-d201-4323-acce-69dcb09a0986.png">

### Version

2.0.0-beta.102

**Comment by 0Miles** [comment]
fixed
