### ISSUE TITLE
🐞 Compiler parses and compiles comments with Vite

### ISSUE THREAD

**Issue by itsezc** [master-co/css#149]
### What happened?

The `css` compiler parses comments in `ts` files and compiles, I've had cases when I've used `// @todo` for internal docs in my TS files the compiler extracts, compiles and validates this, this should not happen as these are commented out and not even in files related to TS or Svelte with Vite.

### Version

v2.0.0-beta.103

**Comment by 1aron** [comment]
@0Miles Fields must be excluded from comments based on file extension like `.html` `.css` in advance.
