### ISSUE TITLE
🐞 Missed some CSS prop values for code-complete like `mx:auto` `mt:auto`

### ISSUE THREAD

**Issue by 1aron** [master-co/css#157]
### What happened?

<img width="812" alt="Screenshot 2023-02-02 at 4 10 49 PM" src="https://user-images.githubusercontent.com/33840671/216272375-b030ea6e-0dc9-4ed7-9258-d861b0d3de74.png">

**Comment by 0Miles** [comment]
🎉 The bug has been fixed in v2.1.31
