### ISSUE TITLE
✨ Can you support "-webkit-image-set" function ?

### ISSUE THREAD

**Issue by jackyyangtw** [master-co/css#162]
### Description

I want to use webp picture as background, but to support more browsers, I still have to use png as alternatives.
[Like this demo](https://codepen.io/atomo/pen/VXrdMV), how to implement this in Master CSS?
[image-set()](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set)

**Comment by 1aron** [comment]
All CSS functions are available out of the box:
```html
<div class="background-image:-webkit-image-set(url('large-balloons.avif')type('image/avif'),url('large-balloons.jpg')type('image/jpeg'))">
```
In this case, if you don't have collocation selectors or media queries and will only use them once, you can use the inline style directly.
