### ISSUE TITLE
🐞 `semantic@media` syntax highlight bug

### ISSUE THREAD

**Issue by 1aron** [master-co/css#176]
### Description

<img width="813" alt="Screenshot 2023-03-09 at 3 31 17 PM" src="https://user-images.githubusercontent.com/33840671/223951469-4d63518a-bd31-434c-82c4-66cb48b71cb3.png">

### System Informations

MacOS, Chrome

**Comment by 0Miles** [comment]
🎉 The bug has been fixed in the next version
