### ISSUE TITLE
✨ `config.keyframes` generated on demand

### ISSUE THREAD

**Issue by 1aron** [master-co/css#181]
### Description

We're considering implementing `@master/keyframes.css` via the new `config.keyframes` API.

master.css.js
```ts
export const config = {
    keyframes: {
        fade: {
            from: { opacity: 0 },
            to: { opacity: 0 }
        },
        ping: {
            '75%,100%' {
                transform: 'scale(2)',
                opacity: 0;
            }
        }
    }
}
```
The syntax is the same as usual:
```html
<div class="@fade|.5s|ease">
or
<div class="animation:fade|.5s|ease">
```
The advantage of this new configuration is that no unused keyframes are generated.

Since keyframes are mostly redefined, `config.keyframes` are not extended deeply:
```ts
if (!config?.override) {
    this.config = extend(defaultConfig, config)
    if ('keyframes' in config) {
        Object.assign(this.config.keyframes, config.keyframes)
    }
}
```

**Comment by itsezc** [comment]
This would be a great addition, centralizing all design decisions under the config would be very useful for design systems.

**Comment by 1aron** [comment]
🎉 Released in https://github.com/master-co/css/releases/tag/v2.0.0-beta.131

**Comment by 1aron** [comment]
🚧 Many exception bugs are being fixed.

- https://beta.css.master.co/sandbox/suqyonzfe7naop?tab=Generated+CSS
- https://beta.css.master.co/docs/animation

**Comment by 1aron** [comment]
Fixed https://github.com/master-co/css/releases/tag/v2.0.0-beta.139
