### ISSUE TITLE
✨ Master CSS ESLint

### ISSUE THREAD

**Issue by 1aron** [master-co/css#185]
An ESLint plugin enforcing a consistent coding style for Master CSS.

.eslintrc.yml
```yml
extends: '@master/css'
```

### Verify the legality of the syntax

```html
<div class="vertical:sup">
                      ┊
                      └─⫸ ❌ `vertical:sup` is not a valid Master CSS syntax ( ✔ vertical-align: super )
```

### Verify syntax conflicts

```html
<div class="block flex">
              ┊     ┊
              ┊     └─⫸ ⚠️ Both `flex` and `block` have the same CSS property applied.
              ┊
              └─⫸ ⚠️ Both `block` and `flex` have the same CSS property applied.
```

### Incorrect order
```html
<div class="m:8 bg:black p:8 fg:white f:24">
```

### Correct order
```html
<div class="m:8 p:8 bg:black fg:white f:24">
```

**Comment by mockingjet** [comment]
Wish for a sorting feature as well.

https://tailwindcss.com/docs/editor-setup#automatic-class-sorting-with-prettier

**Comment by 1aron** [comment]
This is indeed a nice feature. Based on the `config.rules[].order`, it is possible that we can accomplish this.

**Comment by 1aron** [comment]
🎉 `@master/css/class-order` rule is released in https://github.com/master-co/css/releases/tag/v2.0.0-beta.175
