### ISSUE TITLE
🐞 Certain syntaxes display wrong CSS rules

### ISSUE THREAD

**Issue by 1aron** [master-co/css#186]
## There are no preview CSS rules

<img width="834" alt="Screenshot 2023-03-20 at 3 56 32 PM" src="https://user-images.githubusercontent.com/33840671/226279584-0b8006e1-a780-4034-80a7-cf7fab64b8e5.png">

## Incorrect CSS rules

<img width="765" alt="Screenshot 2023-03-20 at 4 01 45 PM" src="https://user-images.githubusercontent.com/33840671/226280117-166dbb85-c409-48e6-a1fc-0adc9c9219fc.png">

It should be:

```css
.font\:12 {
    font-size: 0.75rem
}
```

### Reproduction

Hover property classes in any `.tsx` file.

### System Informations

macOS, VSCode

**Comment by 0Miles** [comment]
🎉 The bug has been fixed in the next version
