### ISSUE TITLE
✨  Force compiler to generate a class 

### ISSUE THREAD

**Issue by ansarizafar** [master-co/css#187]
### Description

Currently in AOT mode classes defined in config file are only generated when they are used which is good but If a class is used dynamically then it is not generated. There should be a way to force compiler to generate a particular class. I propose prefixing a class with ! symbol.

I want to define an error class in master.css.js and use it dynamically in a Svelte app

```javascript
// master.css.js
const config = { 
	classes: {
		!error: 'bg:red-98 fg:rd-40 b:1|solid|red-70'    // Force compiler to generate this class
}

module.exports = { config }
```
Here is how I want to use error class with Svelte.
```svelte
<div class:error={isError}>Something went wrong</div>
```

**Comment by 1aron** [comment]
`!` may be confused with `!important`, please use `options.classes.fixed` in preference.
```js
CSSExtractorPlugin({
    classes: {
        fixed: ['error']
    }
})
```
