### ISSUE TITLE
✨ Create a Svelte preprocess for Master CSS

### ISSUE THREAD

**Issue by 1aron** [master-co/css#194]
### Description

https://svelte.dev/docs#compile-time-svelte-preprocess

The HTML is scanned by the `renderIntoHTML` method of Master CSS and statically injected into the generated CSS rules.

**Comment by 1aron** [comment]
Actually, we don't need to build a svelte preprocessor for SSG and SSR, just keep the current solution to build a `src/hooks.server.ts`
```js
import { renderIntoHTML } from '@master/css'
import { config } from './master.css'

/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
    return await resolve(event, {
        transformPageChunk: ({ html }) => renderIntoHTML(html, config)
    })
}
```

🟢 `src/routes/+page.ts` with `export const ssr = true` ( default )

<img width="1422" alt="Screenshot 2023-03-30 at 2 13 55 PM" src="https://user-images.githubusercontent.com/33840671/228745832-a9a0a217-17d1-4171-89e7-e9c2df9ea023.png">

🔴 `src/routes/+page.ts` with `export const ssr = false`

<img width="1315" alt="Screenshot 2023-03-30 at 2 26 37 PM" src="https://user-images.githubusercontent.com/33840671/228748306-b4bd56c3-0e4d-4c79-86f9-1a5bc165c356.png">

If you use SSR, you will not be able to use Master CSS Progressive Rendering because the HTML of the page is rendered on the client side, and we cannot predict class names.

**Comment by ansarizafar** [comment]
I think this solution will not work with @sveltejs/adapter-static as you can't use any server side file https://kit.svelte.dev/docs/single-page-apps

**Comment by ansarizafar** [comment]
The other benefit of Svelte preprocess is that we can use Master css syntax within Svelte style block.
```html
<style lang="mcss">
.heading {
    fg:blue-70 font:medium p:10
}
</style>
```

**Comment by 1aron** [comment]
> 



> I think this solution will not work with @sveltejs/adapter-static as you can't use any server side file https://kit.svelte.dev/docs/single-page-apps

In Svelte despite setting `ssr=false`, `hooks.server.js` will still be executed at build time. The reason why `@sveltejs/adapter-static` is not applicable is simple, if `ssr` is disabled, then preprocessor resolution will also have no effect because CSR generates HTML at execution time.

So in this case you only have two options:

- [Master CSS AOT](https://beta.css.master.co/docs/guides/svelte/ahead-of-time) (like tailwind)
- [Master CSS JIT](https://beta.css.master.co/docs/guides/svelte/just-in-time)

It's impossible to break through until the browser is open.

**Comment by 1aron** [comment]
> The other benefit of Svelte preprocess is that we can use Master css syntax within Svelte style block.
> 
> ```
> <style lang="mcss">
> .heading {
>     fg:blue-70 font:medium p:10
> }
> </style>
> ```

True, but we have to make sure this syntax works for all frameworks and natively.
