### ISSUE TITLE
🐞 Code-completion not working in react + vite + TS

### ISSUE THREAD

**Issue by TvojTatk0** [master-co/css#225]
### Description

Code-completion is not working on react + TS + vite project. I have to pres control + fn + space in order to see options. 
![image](https://github.com/master-co/css/assets/28844291/4556e499-c2be-4bfe-8d1c-38ae06d13aa7)

### Reproduction

1. create react app using `create vite` with react-ts template
2.  Innit mastercss
3. Instal extension

### System Informations

OS: macOS 13.3.1 
Code: Version: 1.78.2
Extension version: v2.1.35

**Comment by 1aron** [comment]
Do you have this option set? https://beta.css.master.co/docs/guides/language-service#editor-quickSuggestions

**Comment by TvojTatk0** [comment]
No, I have had not. Now, it's working. Thanks 👍 
But, I have notice that "color square" is not showing in `tsx` files. 
![image](https://github.com/master-co/css/assets/28844291/e2594453-7565-4a26-8358-1dcd4660652b)

**Comment by 1aron** [comment]
The latest guidelines will be updated soon.

<img width="1512" alt="Screenshot 2023-05-26 at 7 07 54 PM" src="https://github.com/master-co/css/assets/33840671/44edb037-1d6c-46d2-9437-23106d3a3b86">

Have you tried reloading your VSCode?

**Comment by TvojTatk0** [comment]
Thanks for your help. Now everything woks as expected 👍
