### ISSUE TITLE
📄 Add esm.sh CDN link for importing @master/css

### ISSUE THREAD

**Issue by ije** [master-co/css#230]
### What is the improvement or update you wish to see?

 I would like to see [esm.sh](https://esm.sh) CDN link for importing `@master/css`

### Is there any context that might help us understand?

esm.sh serves `@master/css` as es6 module

```js
import { MasterCSS } from 'https://esm.sh/@master/css@beta'
new MasterCSS({
  colors: {
    primary: '#ff0000'
  }
})
```

### Does the docs page already exist? Please link to it.

https://beta.css.master.co/docs/guides

**Comment by ije** [comment]
btw, @master/css looks promising!

**Comment by 1aron** [comment]
@ije The **esm.sh** CDN link is expected to be added at https://beta.css.master.co/docs/installation#cdns. 😊

**Comment by 1aron** [comment]
@ije 🚀 Launched https://beta.css.master.co/docs/installation/esm-sh

**Comment by ije** [comment]
@1aron thanks
