### ISSUE TITLE
✨ Support logical (vs physical) spacial properties

### ISSUE THREAD

**Issue by merchako** [master-co/css#250]
### Description

**Problem**: Master.co's spacial properties are physical (left, right, top, bottom). I can't use physical properties to support right-to-left languages in the future. For example, [see margin](https://css.master.co/docs/margin):
> `mx:size` → `margin-left: size; margin-right: size`

**Solution**: Offer [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values) by default. 

**Option A**
> `mx:size` → `margin-inline: size`
> or
> `mx:size` → `margin-inline-start: size; margin-inline-end: size;`
> 
> and something like
> `mxs:size` → `margin-inline-start: size;`
> `mxe:size` → `margin-inline-end: size;`

You may want to discuss whether `x` → `inline` and `y` → `block`, or if it would be better to use different initials.

**Option B**
> `mi:size` → `margin-inline: size`
> `mis:size` → `margin-inline-start: size;`
> `mie:size` → `margin-inline-end: size;`

**Comment by 1aron** [comment]
@merchako Option B is perfect. We also anticipate adding a new `padding-inline` series.
