### ISSUE TITLE
✨ Support step-scaling (e.g., Utopia.fyi)

### ISSUE THREAD

**Issue by merchako** [master-co/css#252]
### Description

**Problem:** MasterCSS directly exposes size values in it's API: font-size, margin, padding, etc. All values are arbitrary. This gives infinite options! Sometimes infinite options are good, but for easier developer decision-making, clearer communication with designers, and a better user experience, it helps to use fewer size values. MasterCSS offers these scales for color but not for size.

**Solution:** Offer a step-based scale for typography, spacing, and grid as an add-on or built-in. Clearleft's [Utopia.fyi](https://utopia.fyi) would be a small yet comprehensive model. See this [Utopia.fyi tool for Tailwind](https://github.com/cwsdigital/tailwind-utopia) to compare.

**Intro to Utopia**: https://www.youtube.com/watch?v=DDuGtN-GakA

**Comment by 1aron** [comment]
Similar to this issue?
- https://github.com/master-co/css/issues/155

**Comment by merchako** [comment]
Perfect! (FWIW, I'm personally don't find the t-shirt sizes readable enough, but I'll take what I can get!)
