### ISSUE TITLE
📄 Svelte setup - Reactive fix

### ISSUE THREAD

**Issue by oskar-gmerek** [master-co/css#272]
### What is the improvement or update you wish to see?

Currently docs state that MasterCSS should be set up like this:

```svelte
<CSSProvider config={import("../master.css")}>
        <slot />
</CSSProvider>
```

This will be not reactive and prevent masterCSS to work correctly on page changes.

This can be easy fixed by changing it to this:

```svelte
<svelte:component this={CSSProvider} config={import("../master.css")}>
        <slot />
</svelte:component>
```

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://beta.css.master.co/docs/installation/svelte

**Comment by AristideBH** [comment]
This fix brokes styles on loaded component's and page changes for me
Edit: I didn't update to the last recommended way of installation `Progressive rendering`. It now works !

**Comment by 1aron** [comment]
Fixed documentation https://beta.css.master.co/docs/installation/svelte
