### ISSUE TITLE
Update Twitter Icon

### ISSUE THREAD

**Issue by pragyamishra56** [master-co/css#280]
### Feature should be add
We're enhancing our platform's visual appeal by updating the Twitter icon. This aims to provide a modern look, ensuring visual consistency and engaging user experience. Share your thoughts on this change, and if you plan to contribute through a pull request, let us know your schedule. Your input is invaluable

## Outdated twitter Icon:
![Screenshot 2023-10-06 195048](https://github.com/master-co/css/assets/115208912/84788f8a-8110-45c3-bba8-e1eb06ad6cf1)

**Comment by 1aron** [comment]
We are working on new v2 documentation, and v1 documentation is no longer being updated.
