### ISSUE TITLE
Confusing Returnings of Server Side Rendering API

### ISSUE THREAD

**Issue by JacobLinCool** [master-co/css#29]
### Description

Expected SSR generates a rendered (styles included) HTML content. 
But it seems that it only parses the html and outputs the generated CSS.

confusing returnings:

1. `html` in the output is the same as the input one and useless.
2. `stylesCss` should contain color variables used in HTML.
3. `colorsCss` is always about 20 kb in size without any tree-shaking, no matter what the input is.
4. `colorsMetaContent` is useless, I don't know in which case it will be used.

That is, developers need to inject the uncompleted (without color variables) or unused (too many color variables) CSS into HTML manually, which is not good for DX and performance.

BTW, the SSR example on the document is outdated.

### Reproduction

[Run the test on StackBlitz](https://stackblitz.com/edit/node-mab5nz?embed=1&file=test.ts&hideNavigation=1&view=editor)

```ts
import { render } from "@master/css/render";
import { StyleSheet, Style } from "@master/css";

const target: string[] = [
    `<div class="p:12"></div>`,
    `<div class="font:24 font:56@2xl font:48@lg font:32@md bg:blue-54:hover bg:blue-47 bg:blue-68:active color:orange"></div>`,
];

for (const html of target) {
    test(html);
}

function test(html: string) {
    const key = `render \x1b[93m${html}\x1b[m`;

    console.time(key);
    const result = render(html, { StyleSheet, Style });
    console.timeEnd(key);

    console.log("html:", `\x1b[92m${result.html}\x1b[m`);
    console.log("stylesCss:", `\x1b[96m${result.stylesCss}\x1b[m`);
    console.log("colorsMetaContent:", `\x1b[94m${result.colorsMetaContent}\x1b[m`);
    console.log("length of colorsCss:", `\x1b[95m${result.colorsCss.length}\x1b[m`);
}
```

### System Informations

`@master/css`: `1.17.2`

**Comment by 1Aron** [comment]
@JacobLinCool Sorry for the confusion caused by the old documentation, I will explain all this later with the new documentation.

Our new documentation face will be updated soon. 🤩 Stay tuned.

**Comment by 1Aron** [comment]
@JacobLinCool About the color tree shaking, let me explain first.
In the future we will have three modes:
1. Map colors directly, inline `rgb` in CSS rules ( minimal output )
2. Generate the global CSS Color Variables according to the used colors
3. Pre-generate all CSS Color Variables ( currently preset )
Why use CSS Variables for this? For now, most people still write CSS rules for some reason, so if you want to access the Master's colors, you must go through CSS variables.

**Comment by JacobLinCool** [comment]
@1Aron Thanks for your responding. 

I understand the concepts behind the pre-generating strategy, but it seems not a good idea to use Master CSS variables within native CSS? Master CSS variables are more likely the internal (private) ones to me and should not be accessible by other parties.

If I have to share variables within and without Master CSS, maybe I would like to control the state by myself.

**Comment by 1Aron** [comment]
@JacobLinCool Agree, so there will be three modes for you to choose.

If you want to use Master Colors in CSS files and we didn't generate CSS variables for you, you have to look up the color table and define the variables manually, which will reduce the development experience.

Other CSS frameworks don't do this, so people keep raising this issue.

**Comment by 1Aron** [comment]
@JacobLinCool This issue has been sorted into milestone. 😌 https://github.com/master-co/css/milestone/1

**Comment by 1Aron** [comment]
@JacobLinCool I think we might go with your idea - the preset will map colors and inline the rgb in the CSS rules, for a minimal output.

Thx again. 😌
