### ISSUE TITLE
🐞 `outline:none` is broken

### ISSUE THREAD

**Issue by oskar-gmerek** [master-co/css#296]
### Description

`outline:*` is always rewrited in css as `outline:* solid`. Because of this behavior there is impossible to use `outline:none` because this is translated to `outline:none solid` what is invalid property value.

There is also no unit tests cover that case.

### Reproduction

1. Add class `outline:none` to the input.
2. See the broken css in dev tools.

### System Informations

N/A

**Comment by 1aron** [comment]
@oskar-gmerek Thank you for describing the issue in detail. It has been resolved in https://github.com/master-co/css/releases/tag/v2.0.0-beta.193.
