### ISSUE TITLE
💖 Modify Master CSS configuration without reloading ESLint Server

### ISSUE THREAD

**Issue by 1aron** [master-co/css#298]
### Current

https://github.com/master-co/css/assets/33840671/ffee0e49-b358-45c0-bbcc-beda97bc0d7c

### Expected

No need to reload the ESLint Server.

**Comment by 0Miles** [comment]
https://github.com/master-co/css/assets/8224584/0e4ac4b4-d5d6-4a2e-80e7-d7f15eb0948a
