### ISSUE TITLE
📄 CDN https://cdn.master.co/css@1.0.0 doesn't exist

### ISSUE THREAD

**Issue by TomoyaKuroda** [master-co/css#311]
### What is the improvement or update you wish to see?

On the Setup page, https://css.master.co/docs/setup#using-cdns  
it says  
Pinning your scales to a specific version in production, like https://cdn.master.co/css@1.0.0
But the page says "Failed to resolve the requested file." and it doesn't exist

### Is there any context that might help us understand?

It would be great if you can update the version dynamically like https://cdn.master.co/css@1.37.8

### Does the docs page already exist? Please link to it.

https://css.master.co/docs/setup

**Comment by 1aron** [comment]
The older version cannot be properly referenced on the CDN. Please use a newer version, such as 1.37.8.

**Comment by TomoyaKuroda** [comment]
@1aron I meant I'd appreciate it if you could update the document page so that people don't get confused.
I can contribute to this issue, but I'm not sure which branch to work on.
