### ISSUE TITLE
🐞 normal.css max-width causes many problems

### ISSUE THREAD

**Issue by fightingdreamer** [master-co/css#318]
### Description

Introduced in a8171cfbbc95cb03b5be47bb7f9f09a69e90a47a  `max-width: 100%;` have very big impact on cases when elements are expected to overflow.

Maybe such rules can be put in new package called `master-css-sensible-defaults.css`?

**Comment by 1aron** [comment]
In practice, `img` and `video` may be expected to be limited to a maximum width of `100%`. So, we prefer that you batch cancel the full width of the target elements through the selector:
```html
<div class="max-w:none_:where(img)">
```

**Comment by fightingdreamer** [comment]
I was not aware of that selector in master-css, big thanks!

**Comment by 1aron** [comment]
> I was not aware of that selector in master-css, big thanks!

Because the document is not complete yet 😅 https://beta.css.master.co/docs/state-selectors

**Comment by 1aron** [comment]
@fightingdreamer I've improved the usage instructions.
https://beta.css.master.co/docs/global-styles#responsive-friendly-media-elements
<img width="865" alt="Xnapper-2023-12-22-15 47 23" src="https://github.com/master-co/css/assets/33840671/18fe5555-ee6b-4d62-bf3e-00de33bc7081">

**Comment by fightingdreamer** [comment]
Great!

The lack of documentation is an issue when convincing colleagues to switch from `tailwind-css` / `uno-css`.

**Comment by 1aron** [comment]
@fightingdreamer This is undeniable, and we will improve all documents in RC. Previously, we were still making breakthroughs in R&D and architecture, and the documents have not yet been finalized.

Thx for your support!
