### ISSUE TITLE
Support to RGBA with background-color rule

### ISSUE THREAD

**Issue by Andres6936** [master-co/css#32]
### Description

![image](https://user-images.githubusercontent.com/18540634/170842892-675eec19-049a-4411-af73-03c7878d62ae.png)

Currently, the rules for applying a background color do not support rgba, only rgb.

**Comment by 1Aron** [comment]
@Andres6936 The documentation missed the feature, but it works.

```html
<div class="bg:rgba(255,255,255,.5)"></div>
```

Thx for reporting. 👍🏻

**Comment by Andres6936** [comment]
Thanks @1Aron
