### ISSUE TITLE
🐞 Incorrect hover preview range

### ISSUE THREAD

**Issue by 1aron** [master-co/css#326]
### Description

```tsx
<li>
    <div className="block py:1x fg:light font:12! lh:1.5">
        <Image />{lastCommit.commit.author.name} {$('Last updated')} <TimeAgo timestamp={lastCommit.commit.author.date} />
    </div>
</li>
```
<img width="1105" alt="Screenshot 2024-02-09 at 7 35 27 AM" src="https://github.com/master-co/css/assets/33840671/2909f5bf-a7af-4003-abc9-f6ed7839d170">

**Comment by 0Miles** [comment]
Fixed in [83f5636](https://github.com/master-co/css/commit/83f56361f96f6efc436bfb7532761670c183c1ae)
