### ISSUE TITLE
Doc is a bit outdated(or wrong)

### ISSUE THREAD

**Issue by HaveF** [master-co/css#34]
### Description

e.g.:

https://docs.master.co/styles/setup/react
says:
```
pnpm install @master/styles @master/style @master/normal.css
```
output:
```
dependencies:
+ @master/normal.css 1.9.3
+ @master/style 1.6.0 deprecated
+ @master/styles 1.14.0 deprecated
```

deprecated???
Oh, it seems I should try `pnpm install @master/css`

And can we link the doc src to to bottom of the doc page? Then we can easily address and fix it while reading.

![image](https://user-images.githubusercontent.com/54462/172579488-f64a22d1-18c0-453e-83ca-345099d6e2be.png)

### System Informations

irrelevant

**Comment by 1Aron** [comment]
@HaveF We're currently carrying out a comprehensive revision and rectification of the official website. I'm sorry to let you go through this painful period. It's almost done.

We merged `style` and `styles` into `@master/css`.
