### ISSUE TITLE
🐞 The shorthand for line-height is not working.

### ISSUE THREAD

**Issue by neneodonkor** [master-co/css#350]
### Description

When I use the shorthand `lh:1.25` it does not work. However, when I use `line-height:1.25` it works. The shorthand has been indicated in the documents: https://rc.css.master.co/docs/line-height.

I am using MasterCSS with Nuxt version: 3.11.2 and Vue version: 3.4.21

**Comment by 1aron** [comment]
`lh:` has been deprecated in favor of `leading:` https://github.com/master-co/css/releases/tag/v2.0.0-rc.27

**Comment by neneodonkor** [comment]
> `lh:` has been deprecated in favor of `leading:` https://github.com/master-co/css/releases/tag/v2.0.0-rc.27

Oh wow, okay.
