### ISSUE TITLE
📄 Tailwind Migration Guide: Space Utilities

### ISSUE THREAD

**Issue by pjrundle** [master-co/css#352]
### What is the improvement or update you wish to see?

Many TW users will be using the `space-x|y` utils, for which there isn't a direct replacement.

Suggest to add a short section to cover this, mentioning that MCSS recommends using `gap` instead. 

Reasons could be along the lines of:
* Better selector performance than the universal selector *+*
* Arguably more robust - margins on child elements can still be used without collisions, etc, etc 
* MCSS doesn't have a built in space-x|y util!

"If you really need to do the same thing, you can use the MCSS syntax `mt:12x>*+*`, `ml:12px>*+*` which is equivalent."

### Does the docs page already exist? Please link to it.

https://rc.css.master.co/docs/migration/tailwindcss

**Comment by 1aron** [comment]
Updated at https://rc.css.master.co/guide/migration/tailwindcss#gap-instead-of-space.
