### ISSUE TITLE
🐞 V2 Inconsistent Behavior With Angular

### ISSUE THREAD

**Issue by HealMah** [master-co/css#357]
### Description

Having installed the framework as documented for Angular (18) in a monorepo, some core features (built-in css classes) are not working consistently. Notable, the `bg:color`. See the attached screenshots in Reproduction Section.

### Reproduction

Please see the provided screenshots
![Screenshot_20240609_230718](https://github.com/master-co/css/assets/133438916/790b097a-3581-45f0-a380-16459df94f19)
![Screenshot_20240609_230811](https://github.com/master-co/css/assets/133438916/e4cae682-8486-4d9d-a836-fd74eae33cd3)
![Screenshot_20240609_230850](https://github.com/master-co/css/assets/133438916/54894296-e205-4add-adbd-6a5b923e6bb1)
![Screenshot_20240609_230919](https://github.com/master-co/css/assets/133438916/baa79425-e9f9-4991-8c65-fe76e1bdf177)

**Comment by 1aron** [comment]
@HealMah There are no intermediate values ​​for v2 colors, see https://rc.css.master.co/reference/colors. Additionally, the `bg:red` `fg:yellow` defaults rely on the light/dark classes on `<html class="light">`. https://rc.css.master.co/reference/base-colors

![image](https://github.com/master-co/css/assets/33840671/e838935e-11d7-4e3a-b015-e08c4f2a0d2e)

**Comment by HealMah** [comment]
> @HealMah There are no intermediate values ​​for v2 colors, see https://rc.css.master.co/reference/colors. Additionally, the `bg:red` `fg:yellow` defaults currently rely on the light/dark classes on `<html>`. https://rc.css.master.co/reference/base-colors
> 
> ![image](https://private-user-images.githubusercontent.com/33840671/338013446-e838935e-11d7-4e3a-b015-e08c4f2a0d2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzE3MjYsIm5iZiI6MTcxNzk3MTQyNiwicGF0aCI6Ii8zMzg0MDY3MS8zMzgwMTM0NDYtZTgzODkzNWUtMTFkNy00ZTNhLWIwMTUtZTA4YzRmMmEwZDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDIyMTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMTAzOWM2MDAxZTYyZjk5ZWQ3OTA5NzMyZThmNWQ1MjUyOGJjNTg5MjM2YmUwMTU2Njk0OGU3ZTY2NzY5NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1PA0AQJtDOQn_2xTAzsjpTbSjCq9wXddaBNBXngGGv8)

Ooops, obviously I am not good with this latest version yet. But, "No intermediate values"???.
 Anyways, no doubt, this is "Master Css". IT'S GREAT, so kudos to you and your team.

**Comment by HealMah** [comment]
Please may I know why one of the following is working but not the other? And this is with classs 'light' on the html element - please see the screenshots.
![Screenshot_20240610_215640](https://github.com/master-co/css/assets/133438916/4cf8bc91-136f-4fdf-bcd7-7b16efdac476)
![Screenshot_20240610_215713](https://github.com/master-co/css/assets/133438916/5ce95434-9802-456b-b425-3c8ef34ab86b)

Besides, I don't know the real reason behind mandating assigning the theme class ('light', 'black', or otherwise) for colors to work properly, BUT - it seems counter-productive, sorry to say. WHAT IF I DON'T WANT to use this framework for managing themes? Color 'red' should be red, what bg is and isn't shouldn't be a burden on the framework - the developer should know enough about his color system! I think this is how the v1 works.

The moment there is not a theme class on any parent, MOST colors go blank - THAT'S WEIRD! Or am I missing something?
I hope you understand my concerns, PLEASE do help enlighten us SIR!

**Comment by 1aron** [comment]
@HealMah In v2, only `red-5` `red-10` `red-20` `red-30` ... are available. We value the real experience of developers and have indeed re-evaluated the solution of not driving color through `html.light` `html.dark`.

**Comment by 1aron** [comment]
@HealMah As of **v2.0.0-rc.42** it is no longer necessary to add `<html class="light">` to drive colors.
