### ISSUE TITLE
🐞 Issues with peer dependencies found

### ISSUE THREAD

**Issue by MarkSky** [master-co/css#369]
### Description

I tried to update eslint from version 8 to version 9, and got error message:
```
 WARN  Issues with peer dependencies found
.
└─┬ @master/eslint-config-css 2.0.0-rc.45
  └─┬ @master/eslint-plugin-css 2.0.0-rc.45
    ├─┬ @typescript-eslint/utils 7.18.0
    │ └── ✕ unmet peer eslint@^8.56.0: found 9.12.0
    └─┬ typescript-eslint 7.18.0
      ├── ✕ unmet peer eslint@^8.56.0: found 9.12.0
      ├─┬ @typescript-eslint/parser 7.18.0
      │ └── ✕ unmet peer eslint@^8.56.0: found 9.12.0
      └─┬ @typescript-eslint/eslint-plugin 7.18.0
        ├── ✕ unmet peer eslint@^8.56.0: found 9.12.0
        └─┬ @typescript-eslint/type-utils 7.18.0
          └── ✕ unmet peer eslint@^8.56.0: found 9.12.0
```

### Reproduction

1. use `pnpm i` to install.
2. got warning in consol.

### System Informations

Node: 22.3.0
@master/colors: ^2.1.0
@master/css: ^2.0.0-rc.45
@master/css.vue: ^2.0.0-rc.45
@master/normal.css: ^3.1.0
@eslint/js: ^9.12.0
@master/eslint-config-css: ^2.0.0-rc.45
eslint: ^9.12.0
typescript-eslint: ^8.8.0

**Comment by 1aron** [comment]
Fixed in https://github.com/master-co/css/releases/tag/v2.0.0-rc.46
