### ISSUE TITLE
Column gap and row gap

### ISSUE THREAD

**Issue by karchung0930** [master-co/css#38]
### Description

There are `grid-column-gap` and `grid-row-gap` for grid layout. But currently, we only can use the general `gap` property.

We often only need the gap for either column or row instead of both of them together.

**Comment by 1Aron** [comment]
We've missed `gap-x` and `gap-y` in the Gap documentation. It works.

**Comment by 1Aron** [comment]
🎉 Improved. https://docs.master.co/css/gap
