### ISSUE TITLE
Extend Semantics doesn't work

### ISSUE THREAD

**Issue by karchung0930** [master-co/css#39]
### Description

I'm making configurations directly in the HTML as described here: https://docs.master.co/css/customization#other-directly-in-index-html

It's working for `Style.extend('classes',{})` but `Style.extend('semantics',{})` wont work.
Below is the full code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
   <link href="https://unpkg.com/@master/normal.css" rel="stylesheet">
   <script>
      /* 1. Prevent @master/css from initializing automatically */
      window.MasterCSSManual = true;
   </script>
   <script src="https://cdn.master.co/css"></script>
   <script >
      /* 2. Configure your initial options here ... */
      const Style = window.MasterStyle;
      Styles.extend('semantics', {
         fontFamily: {
            my-custom-font: 'Roboto Slab', serif
         }
      });
      /* 3. Manually initialize */
      window.initMasterCSS();
   </script>
</head>
<body>
   <button class="btn">Ok</button>
</body>
</html>
```

### System Informations

Browser: Firefox Developer

**Comment by 1Aron** [comment]
`Styles` and `Style` are different!
```js
const Styles = window.MasterStyles;
```

**Comment by karchung0930** [comment]
@1Aron Apparently that's my personal typo, it's still not working. Can you at least try the code yourself...Please

I'm using the WordPress function and not sure if this causes the problem, below is the code:
```
wp_add_inline_script(
   'master',
   'const Style = window.MasterStyle;
    Style.extend("semantics", {
      fontFamily: {
         roboto: "Roboto, sans-serif"
      }
    });
   window.initMasterCSS();',
);
```

**Comment by 1Aron** [comment]
@karchung0930 Have you tried the [example](https://stackblitz.com/edit/mastercss-customization-example?file=styles%2Fmaster.css.js) ?

Extending `values` and `semantics` must access `Styles` instead of `Style`.
```js
Styles = window.MasterStyles;
Styles.extend("semantics", {
    fontFamily: {
       roboto: "Roboto, sans-serif"
    }
});
```

**Comment by karchung0930** [comment]
@1Aron I've just tried the below code with `Styles` but also not working.
```
wp_add_inline_script(
   'master',
   'const Styles = window.MasterStyle;
   Styles.extend("semantics", {
      fontFamily: {
         roboto: "Roboto, sans-serif"
      }
   });
   window.initMasterCSS();',
);
```

So far I got two thoughts:
1) Maybe` Styles.extend("semantics", {}` won't work if making it direct in index.html?
2) There is some kind of mistakes in the code because it's in a PHP file with a WordPress function, maybe the pattern like quotes are wrong, something like that.

**Comment by 1Aron** [comment]
@karchung0930 If you have initialized Master CSS before this, you must use instead:
```js
wp_add_inline_script(
   'master',
   `
   const Styles = window.MasterStyles
   Styles.extend("semantics", {
      fontFamily: {
         roboto: "Roboto, sans-serif"
      }
   });
   window.MasterStyleSheet.refresh();
   `,
);
```
However, there is still a bug with your current code.
change
```js
const Styles = window.MasterStyle;
```
to
```js
const Styles = window.MasterStyles;
```
It's easy to misunderstand `Style` and `Styles` here, so be careful.

**Comment by karchung0930** [comment]
@1Aron Yep, it's working perfectly now. Thank you so much.

But I don't understand `window.MasterStyleSheet.refresh();`, as you can in the screenshot, I only use `window.initMasterCSS()` and it works. I'm not sure if I have initialized Master CSS before, I just follow the tutorial by using the CDNs (only added one time at one place).
![screenshot](https://user-images.githubusercontent.com/73235650/178250071-e11c0e98-b03f-4f01-88c7-25f7d6b5b8ff.png)

**Comment by 1Aron** [comment]
@karchung0930 If you need to update the APIs after initialization, you must execute `.refresh()`. Otherwise, you only need to execute `init()`.

**Comment by karchung0930** [comment]
@1Aron Is `init()` equal to `window.initMasterCSS()`? Since the `window.MasterCSSManual` is set to `true`, I believe Master CSS is not initialized before. Therefore, `.refresh()` is not necessary in this case, do you agree?

**Comment by 1Aron** [comment]
@karchung0930 Correct, we'll continue to improve the documentation.
