### ISSUE TITLE
hide do not create element

### ISSUE THREAD

**Issue by karchung0930** [master-co/css#40]
### Description

The `hide` isn't adding the class `display: none;` on `::before`, instead the content won't be generated at all with class `hide`.

This makes me to unable to use JavaScript to select the `element::before`. My use case is to remove the `hide` after the button is clicked but now the `element::before` isn't generated so this is impossible,

### System Informations

Browser: Firefox Developer

**Comment by 1Aron** [comment]
@karchung0930 Can you provide a https://stackblitz.com/ example to reproduce the problem? Not very clear about your question.
![Screen Shot 2022-07-20 at 9 39 27 PM](https://user-images.githubusercontent.com/33840671/179996625-2a4ffc52-fd59-4060-a34b-15e458f9393e.jpg)

**Comment by 1Aron** [comment]
@karchung0930 `hide::after` will of course hide the after pseudo-element inside `<div>::after</div>`.
