### ISSUE TITLE
🐞 `font-color:$(variable)` not working with scoped variables

### ISSUE THREAD

**Issue by gammx** [master-co/css#55]
### Description

I want to use a CSS variable defined outside `:root`, eg:
```css
:root {
    --gyan-100: #00FF75;
}

.theme-dark {
    --text-tertiary: #8B98AC;
}
```
It works if I use a global variable:
```html
<p className="font-color:$(gyan-100)">...</p>
```
![generated-class1](https://user-images.githubusercontent.com/50937087/186543051-afa1db2a-9d79-4192-bba2-e4a278a54bde.png)
But not with this one:
```html
<p className="font-color:$(text-tertiary)">...</p> // Fail!
```
![generated-class](https://user-images.githubusercontent.com/50937087/186543101-bbdef9e8-2a91-4e2e-b911-116bc054cc99.png)

`.theme-dark` is correctly applied btw, and changing the value through developer tools returns the expected color.

![html](https://user-images.githubusercontent.com/50937087/186543337-f4459c36-cc4d-4f2d-8386-0d3b9d0f56b5.png)

Any ideas of what is happening? (:

### System Informations

Browser: Microsoft Edge (Chromium) 103.0.1264.51
OS: Zorin OS (x64)
Node.js: 18.5.0
Package Manager: npm 8.12.1

**Comment by 1Aron** [comment]
@gammx What's your Master CSS version now? It works for me.

Generated CSS

![Screen Shot 2022-08-25 at 10 31 14 PM](https://user-images.githubusercontent.com/33840671/186693398-f0930373-1d92-4431-98c4-394d006c1aa7.jpg)

JIT in console

![Screen Shot 2022-08-25 at 10 32 27 PM](https://user-images.githubusercontent.com/33840671/186693416-bb7e0dfe-06c6-4a76-b8bc-187a67cdd281.jpg)

**Comment by gammx** [comment]
I'm using the latest version, I'm also using the manually/hybrid rendering setup with Next.js (https://docs.master.co/css/setup/nextjs#hybrid-rendering), Here are some things I've noticed:
- If I use Next.js with SCSS and declare the scoped variable in a `.scss` file it doesn't work, but it works with a `.css` file
- If I refresh the page, the class is generated but it's using the color as variable `--#F9F9F9`:
```html
<style id="master-css">
    .font-color\:\$\(text-primary\){color:var(--#F9F9F9)}
</style>
```
- If I remove the manual initialization declared in my `_document.tsx` file, it works with both `.scss` and `.css` but it's weird because the style tag gets empty:
```html
<style id="master-css"></style>
```

So I guess it's something with the Next.js setup... maybe?

**Comment by gammx** [comment]
Ok I managed to get it working removing some conflicts with other classes, but it works only if I remove hybrid rendering, I get this with the https://docs.master.co/css/setup/nextjs#hybrid-rendering setup:
```html
<style id="master-css">
    .font-color\:\$\(text-primary\){color:var(--#F9F9F9)} /*instead of var(--text-primary)*/
</style>
```
And it works if I remove the hybrid rendering code, but the style tag gets empty:

![css](https://user-images.githubusercontent.com/50937087/186728414-b330e62e-b68d-4b5a-bb5f-1183e5e3aff1.png)

**Comment by 1Aron** [comment]
If it is JIT, Master CSS will use the native `style.sheet` API to manipulate CSS rules. You can't see it through inspect, but you can use `console.log`.

**Comment by gammx** [comment]
Nice, well, I removed the hybrid rendering setup to stop getting the `color:var(--#F9F9F9)` thing, thanks:)
