### ISSUE TITLE
✨ Global tokens 

### ISSUE THREAD

**Issue by ansarizafar** [master-co/css#56]
### Description

Global token are important for building a design system but currently its not possible to define a global token using Styles.extend. We should be able to use Styles.extend for defining a global token.

```
Styles.extend('global', { 
size: {10: '10px},
'border-sm': '1px'

})

**Comment by 1aron** [comment]
in v2.0 beta, you can do like this:
```js
/* ./master.css.js */

const sizing = {
    '2x': '2rem',
    '3x': '3rem',
}

const borderSizing = 

module.exports = {
    values: {
        Width: sizing,
        Height: sizing,
        Border: {
            xs: '1px'
        }
        ...
    }
}

```

**Comment by 1aron** [comment]
@ansarizafar The feature you want are now supported! https://github.com/master-co/css/discussions/79#discussioncomment-4033705
