### ISSUE TITLE
✨ Support sveltekit

### ISSUE THREAD

**Issue by alpap** [master-co/css#58]
### Description

It would be awesome if there was documentation about how to integrate with sveltekit

**Comment by Andres6936** [comment]
Why did you close it, have you found a way to use it with SvelteKit?

**Comment by 1aron** [comment]
@Andres6936 https://docs.master.co/css/setup/svelte
In v1, you just need to import `@master/css` as a normal JS package and the JIT engine will be enabled immediately.
In v2, we'll include AOT setup guides for each framework.

**Comment by 1aron** [comment]
@alpap @Andres6936 
Now the AOT mode of 2.0 Beta already supports Svelte Kit, but it is not yet able to scan the class name of the entry file like `app.html`, this is not a big problem, but we're looking for best practices.

Check out the Svelte Kit + Master CSS example: https://github.com/master-co/css/tree/beta/examples/svelte-kit

**Comment by AristideBH** [comment]
> * Initialize `MasterCSSVitePlugin`: [`beta`/examples/svelte-kit/src/routes/%2Blayout.svelte#L4](https://github.com/master-co/css/blob/beta/examples/svelte-kit/src/routes/%2Blayout.svelte?rgh-link-date=2022-11-24T06%3A55%3A51Z#L4)

Wrong link for this one ref ;) : https://github.com/master-co/css/blob/beta/examples/svelte-kit/vite.config.ts#L8

**Comment by 1aron** [comment]
After some refactoring and fixes, Master CSS v2 AOT is fairly stable in Svelte Kit. 🎉

<img width="1331" alt="Screenshot 2022-12-17 at 1 21 57 AM" src="https://user-images.githubusercontent.com/33840671/208241933-571f5eb2-760b-45ab-823d-7091295d8426.png">

Check out the latest example and guide: https://github.com/master-co/css/tree/beta/examples/svelte-with-progressive-rendering.
