### ISSUE TITLE
✨ Neovim LSP

### ISSUE THREAD

**Issue by nexxeln** [master-co/css#71]
### Description

Very excited for master, but for now there's only a vscode extension. If you can make a Language Server Protocol (LSP), then master can be supported across multiple IDEs like Neovim, etc.

**Comment by 0Miles** [comment]
@nexxeln  There are currently no plans to make a LSP.
When there is a space in the future, we will make it.

**Comment by nexxeln** [comment]
> @nexxeln LSP is currently not on our short-term schedule, but we'd love to do it when the core tasks are all done.

That sounds good!
