### ISSUE TITLE
cdnjs instead of jsDelivr as CDN

### ISSUE THREAD

**Issue by pierredewilde** [master-co/css#72]
### Description

https://cdn.master.co/css is currently redirected to https://cdn.jsdelivr.net/npm/@master/css.

[cdnjs](https://cdnjs.com/) offers a better compression (brotli) than jsDelivr (gzip).

Comparison of the usage statistics of cdnjs vs. jsDelivr
https://w3techs.com/technologies/comparison/cd-cdnjs,cd-jsdelivr

**Comment by jimaek** [comment]
hey, jsDelivr also supports brotli `content-encoding: br`.
In addition its a multi-CDN (resulting in high-availability https://twitter.com/jsDelivr/status/1539143174123311107) and it's under active development (ESM functionality, new site, new API...)

**Comment by pierredewilde** [comment]
Thanks.
