### ISSUE TITLE
📄 3xl is incorrectly documented as 1600 instead of 1920

### ISSUE THREAD

**Issue by pierredewilde** [master-co/css#73]
### What is the improvement or update you wish to see?

incorrect: `3xl | @media (min-width: 1600px) { }`

correct: `3xl | @media (min-width: 1920px) { }`

as indicated in `breakpoints.js`

### Is there any context that might help us understand?

https://github.com/master-co/css/blob/main/src/breakpoints.js

### Does the docs page already exist? Please link to it.

https://docs.master.co/css/breakpoints

**Comment by 1Aron** [comment]
Thanks for reporting the bug! We'll fix it in the new documentation.
