### ISSUE TITLE
✨ MDN Docs for language service

### ISSUE THREAD

**Issue by itsezc** [master-co/css#95]
### Description

Add inline MDN docs support for classes, highlighting browser support, issues and description of the feature

**Comment by 1aron** [comment]
Good suggestion, we expect to implement the API with VSCode CSS Language Service to make hints the same as native CSS. https://github.com/microsoft/vscode-css-languageservice/blob/main/src/data/webCustomData.ts #129

**Comment by 0Miles** [comment]
🎉 The feature has been added in v2.1.23
